### ISSUE TITLE
Haojie Zhang: 1.tensor-networks

### ISSUE THREAD

**Issue by lovemy569** [CodingThrust/NumericTrainingCamp#9]
Reproduce the paper by Tang W, Tu H H, Wang L. Continuous matrix product operator approach to finite temperature quantum states[J]. Physical Review Letters, 2020, 125(17): 170604 [↩](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.125.170604)

Members

Haojie Zhang

Link to GitHub repository:
https://github.com/lovemy569/CMPO-For-Finite-Temperature

**Comment by GiggleLiu** [comment]
Merged to registry: https://github.com/CodingThrust/NumericTrainingCamp/tree/main/projects

**Comment by lovemy569** [comment]
update link: https://github.com/lovemy569/cMPO.jl

**Comment by GiggleLiu** [comment]
Noted.
